name: LcBattle
version: 1.0
main: com.lcbattle.LcBattlePlugin
commands:
  lcbt:
    description: Comandos de administración de LcBattle.
    usage: /lcbt <comando>
    aliases:
      - lcbt
    permission: lcbattle.admin

  lcbt top:
    description: Ver y gestionar los tops de jugadores.
    usage: /lcbt top <wins|kills|time> [edit|create|remove|reset] [numero]
    permission: lcbattle.admin

  lcbt setlobby:
    description: Establecer el spawn de los jugadores en el lobby.
    usage: /lcbt setlobby
    permission: lcbattle.admin

  lcbt setspawn:
    description: Establecer el spawn para los jugadores en espera.
    usage: /lcbt setspawn
    permission: lcbattle.admin

  lcbt lcoins:
    description: Gestionar los Lcoins de los jugadores.
    usage: /lcbt lcoins <edit|set|remove> <jugador> [monto]
    permission: lcbattle.admin

  lcbt rango:
    description: Gestionar el rango de los jugadores (próximamente).
    usage: /lcbt rango
    permission: lcbattle.admin

  lcbt import:
    description: Importar un mundo externo como un mapa.
    usage: /lcbt import <mundo>
    permission: lcbattle.admin

  lcbt save:
    description: Guardar un mapa modificado.
    usage: /lcbt save <mapa>
    permission: lcbattle.admin

  lcbt edit:
    description: Editar mapas, kits, y configuraciones.
    usage: /lcbt edit <mapa> <tp|save|max_player|min_player|time> [numero]
    permission: lcbattle.admin

  lcbt reset:
    description: Reiniciar el plugin para guardar cambios o corregir errores.
    usage: /lcbt reset
    permission: lcbattle.admin

  lcbt help:
    description: Mostrar la lista de comandos disponibles y su uso.
    usage: /lcbt help
    permission: lcbattle.admin
