name: LcBattle
version: 1.0
main: com.lcbattle.LcBattlePlugin
api-version: 1.16
commands:
  teleportmap:
    description: Teletransportarse a un mapa.
    usage: /teleportmap <mapa>
    permission: lcbattle.teleport
  importworld:
    description: Importar un mundo al plugin como mapa.
    usage: /importworld <mundo>
    permission: lcbattle.import
