name: LC-Battle
version: 1.0
main: com.lcbattle.LcBattlePlugin
api-version: 1.13
commands:
  lcbattle:
    description: Comandos para gestionar las batallas y arenas.
    usage: /<command> <create|start|stop|join|leave|setspawn|stats|leaderboard>
    aliases:
      - battle
    subcommands:
      create:
        description: Crea una nueva arena de batalla.
        usage: /lcbattle create <arena>
      start:
        description: Inicia una batalla en la arena especificada.
        usage: /lcbattle start <arena>
      stop:
        description: Detiene una batalla y reinicia los jugadores.
        usage: /lcbattle stop <arena>
      join:
        description: Permite a los jugadores unirse a una arena de batalla.
        usage: /lcbattle join <arena>
      leave:
        description: Permite a los jugadores salir de una arena de batalla.
        usage: /lcbattle leave <arena>
      setspawn:
        description: Establece el punto de aparición de un jugador dentro de una arena.
        usage: /lcbattle setspawn <arena> <jugador>
      stats:
        description: Muestra las estadísticas de combate de un jugador.
        usage: /lcbattle stats <jugador>
      leaderboard:
        description: Muestra el ranking de los jugadores con mejores puntuaciones.
        usage: /lcbattle leaderboard

  lcbt:
    description: Comandos para la administración de arenas y configuraciones del plugin.
    usage: /<command> <top|setlobby|setspawn|lcoins|rango|import|save|edit|reset|help>
    aliases:
      - adminbattle
    subcommands:
      top:
        description: Gestiona los tops de victorias, asesinatos, o tiempo de juego.
        usage: /lcbt top {wins|kill|time} <edit|create|remove|reset> [numero]
        subcommands:
          edit:
            description: Edita un top existente.
            usage: /lcbt top {wins|kill|time} edit <numero>
          create:
            description: Crea un nuevo top en el lugar donde esté el administrador.
            usage: /lcbt top {wins|kill|time} create
          remove:
            description: Elimina un top específico.
            usage: /lcbt top {wins|kill|time} remove <numero>
          reset:
            description: Reinicia todos los tops.
            usage: /lcbt top {wins|kill|time} reset

      setlobby:
        description: Establece el punto de aparición de todos los jugadores en el lobby.
        usage: /lcbt setlobby

      setspawn:
        description: Establece el punto de aparición de los jugadores mientras esperan la partida.
        usage: /lcbt setspawn

      lcoins:
        description: Modifica los LCoins de un jugador.
        usage: /lcbt lcoins <edit|set|remove> <jugador> <monto>
        subcommands:
          edit:
            description: Edita la cantidad de LCoins de un jugador.
            usage: /lcbt lcoins edit <jugador> <monto>
          set:
            description: Establece una cantidad de LCoins a un jugador.
            usage: /lcbt lcoins set <jugador> <monto>
          remove:
            description: Elimina una cantidad de LCoins a un jugador.
            usage: /lcbt lcoins remove <jugador> <monto>

      rango:
        description: Asigna un rango a un jugador (proximamente).
        usage: /lcbt rango
        permission: lcbattle.admin
        permission-message: "Este comando está disponible próximamente."

      import:
        description: Importa un mundo externo y lo convierte en un mapa jugable.
        usage: /lcbt import <mundo>

      save:
        description: Guarda las modificaciones realizadas en un mapa.
        usage: /lcbt save <mapa>

      edit:
        description: Edita la configuración de un mapa.
        usage: /lcbt edit <mapa> <tp|save|max_player|min_player|time> [valor]

      reset:
        description: Reinicia el plugin para guardar cambios internos.
        usage: /lcbt reset

      help:
        description: Muestra la lista de todos los comandos disponibles.
        usage: /lcbt help
